---
openapi: 3.0.2
info:
  title: rpi-pwm
  version: 1.0.0
  description: "API for \"rpi-pwm\" enabling users to remotely control app settings\
    \ (e.g., fan speeds)"
  license:
    name: GNU AGPLv3
    url: https://www.gnu.org/licenses/agpl.txt
servers:
- url: "http://{subdomain}.{localdomain}/api/"
  description: Local raspberry using reverse proxy w/ dedicated local domain
  variables:
    subdomain:
      default: rpipwm
      description: Subdomain used by reverse proxy to map requests on same port to
        specific webapps
    localdomain:
      default: rpi.lan
      description: 'Local domain of raspberry '
paths:
  /app/config:
    summary: Allows user to view config of app
    description: Singleton resource of config flags
    get:
      responses:
        "200":
          $ref: '#/components/responses/app-config_singleton'
      summary: Returns current config flags
      description: Returns current config flags
    put:
      requestBody:
        description: Config flags consisting of app and pwm config
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AppConfig'
            examples:
              singletonConfig:
                value:
                  app:
                    fanOn: true
                    loggingEnabled: true
                    loggingLevel: WARN
                    DCUpdateIntervalInSec: 3
                  pwm:
                    gpioPin: 12
                    invertSignal: true
                    minDCInPerc: 20
                    maxDCInPerc: 95
        required: true
      responses:
        "200":
          $ref: '#/components/responses/app-config_singleton'
        "400":
          $ref: '#/components/responses/HTTPError-BadRequest'
      summary: Updates config flags
      description: Updates config flags
  /app/fanCurves:
    summary: Enables user to view all fan curves or to add a new one (up to 10 max)
    description: Collection resource for fan curves
    get:
      responses:
        "200":
          $ref: '#/components/responses/app-fanCurves_collection'
      summary: Returns list of all available fan curves
      description: Returns list of all available fan curves
    post:
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AppFanCurveBase'
            examples:
              appFanCurveBase:
                value:
                  name: Quiet
                  fanCurveSeries:
                  - tempInCels: 30
                    fanSpeedInPerc: 40
                  - tempInCels: 35
                    fanSpeedInPerc: 50
        required: true
      responses:
        "201":
          $ref: '#/components/responses/app-fanCurves_singleton'
        "400":
          $ref: '#/components/responses/HTTPError-BadRequest'
      summary: Adds new fan curve
      description: Adds new fan curve
    parameters:
    - examples:
        name:
          value: Quiet-
      name: name
      description: Filter for fan curves whose name is similar to `name`
      schema:
        type: string
      in: query
      required: true
  /app/fanCurves/{id}:
    summary: "Allows user to view, update or delete fan curve corresponding to specified\
      \ \"id\""
    description: Singleton resource for fan curves
    get:
      responses:
        "200":
          $ref: '#/components/responses/app-fanCurves_singleton'
        "404":
          $ref: '#/components/responses/HTTPError-NotFound'
      summary: Returns requested fan curve whose id corresponds to specified "id"
      description: Returns requested fan curve whose id corresponds to specified `id`
    put:
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AppFanCurve'
            examples:
              singletonFanCurve:
                value:
                  name: some text
                  fanCurveSeries:
                  - tempInCels: 60
                    fanSpeedInPerc: 66
                  - tempInCels: 44
                    fanSpeedInPerc: 42
                  - tempInCels: 53
                    fanSpeedInPerc: 56
        required: true
      responses:
        "200":
          $ref: '#/components/responses/app-fanCurves_singleton'
        "400":
          $ref: '#/components/responses/HTTPError-BadRequest'
        "404":
          $ref: '#/components/responses/HTTPError-NotFound'
      summary: Updates requested fan curve whose id corresponds to specified "id"
      description: Updates requested fan curve whose id corresponds to specified `id`
    delete:
      responses:
        "204":
          description: Empty body
        "404":
          $ref: '#/components/responses/HTTPError-NotFound'
        "423":
          $ref: '#/components/responses/HTTPError-Locked'
      summary: Deletes fan curve whose id correspond to specified "id"
      description: Deletes fan curve whose id correspond to specified `id`
    parameters:
    - examples:
        fanCurveId:
          value: 4731ab6a-433b-11ec-8321-c3a754deb306
      name: id
      description: "Id of the fan curve (generated, i.e., surrogate key)"
      schema:
        type: string
      in: path
      required: true
  /system/info:
    summary: Allows user to obtain information about the currently used SW & HW
    description: Singleton resource of system info
    get:
      responses:
        "200":
          $ref: '#/components/responses/system-info_singleton'
      summary: Returns information about used system (SW & HW)
      description: Returns information about used system (SW & HW)
  /system/topTenProcesses:
    summary: Allows user to view the top 10 processes which utilize the majority of
      CPU time (dynamically aggregated)
    description: "Collection resource for top 10 processes (dynamically aggregated;\
      \ NOTE: MIGHT NOT WORK IN DOCKER)"
    get:
      responses:
        "200":
          $ref: '#/components/responses/system-topTenProcesses_collection'
      summary: Returns list of top 10 processes using the most CPU time
      description: Returns list of top 10 processes using the most CPU time
  /system/topTenProcesses/{nr}:
    summary: Allows user to view process w/ nr highest CPU utilization at current
      moment
    description: "Singleton resource for top 10 processes (dynamically aggregated;\
      \ NOTE: MIGHT NOT WORK IN DOCKER)"
    get:
      responses:
        "200":
          $ref: '#/components/responses/system-topTenProcesses_singleton'
        "404":
          $ref: '#/components/responses/HTTPError-NotFound'
      summary: Returns requested process whose current CPU utilization corresponds
        to specified nr in ranking
      description: Returns requested process whose current CPU utilization corresponds
        to specified `nr` in ranking
    parameters:
    - examples:
        topTenProcessNr:
          value: "2"
      name: nr
      description: Corresponds to process w/ `nr` highest CPU utilization at current
        moment
      schema:
        type: integer
      in: path
      required: true
  /app/tempDCHistory:
    summary: "Returns temperature- & fan history over last 10 min. Note: Time delta\
      \ b/w each item depends on config-flag \"DCUpdateIntervalInSec\""
    description: Collection resource for fan- & DC history
    get:
      responses:
        "200":
          $ref: '#/components/responses/app-tempDCHistory_collection'
      summary: Returns temperature- & fan history over last 10 min.
      description: Returns temperature- & fan history over last 10 min.
  /app/logs/:
    summary: "Enables user to view app logs (Note: Might return nothing if logging\
      \ was disabled via config flag \"loggingEnabled\")"
    description: Collection resource for logs
    get:
      responses:
        "200":
          $ref: '#/components/responses/app-logs_collection'
      summary: Returns list of all available fan curves
      description: Returns list of all available fan curves
components:
  schemas:
    SystemStats:
      title: Root Type for StatsSystem
      description: Current stats of the system
      required:
      - cpuClockInMhz
      - cpuTempInCels
      - cpuTotalUtilInPerc
      - fanDCInPerc
      type: object
      properties:
        cpuTotalUtilInPerc:
          format: int32
          description: Current total CPU utilization in percent (retrieved via `ps
            -A -o pcpu | tail -n+2 | paste -sd+ | bc`)
          type: integer
          readOnly: true
          example: "43"
        cpuClockInMhz:
          format: int32
          description: Current frequency of CPU (core 0 ?) in MHz  (retrieved via
            `cat /sys/devices/system/cpu/cpu0/cpufreq/cpuinfo_cur_freq` / 1000)
          type: integer
          readOnly: true
          example: "800"
        cpuTempInCels:
          format: int32
          description: Current temperature of CPU (core 0 ?) in Celsius
          type: integer
          readOnly: true
          example: "32"
        fanDCInPerc:
          format: int32
          description: Current dutycycle of fan in percent
          type: integer
          readOnly: true
          example: "32"
      example:
        cpuTotalUtilInPerc: 43
        cpuTempInCels: 32
        cpuClockInMhz: 800
        fanDCInPerc: 32
    SystemInfo:
      title: Root Type for SystemInfo
      description: Contains information about the system itself
      required:
      - hwBootloaderVer
      - hwCpuHw
      - hwCpuRev
      - hwPiBoardRev
      - execUser
      type: object
      properties:
        osKernel:
          description: ' Current kernel version (retrieved via `uname -srvmo`)'
          type: string
          example: "Linux 5.10.63-v7l+ #1459 SMP Wed Oct 6 16:41:57 BST 2021 armv7l\
            \ GNU/Linux"
        hwPiBoardRev:
          description: Pi board revision (retrieved via `cat /proc/cpuinfo`)
          type: string
          readOnly: true
          example: Raspberry Pi 4 Model B Rev 1.1
        hwCpuHw:
          description: Part number of SoC (retrieved via `cat /proc/cpuinfo`)
          type: string
          readOnly: true
          example: BCM2711
        hwCpuRev:
          description: SoC revision (retrieved via `cat /proc/cpuinfo`)
          type: string
          readOnly: true
          example: c03111
        hwBootloaderVer:
          description: Current bootloader version (retrieved via `vcgencmd bootloader_version`)
          type: string
          readOnly: true
          example: c2f8c388c4ee37ad709ace403467d163e8dd91ce (release)
        execUser:
          description: "User on the system under which the execution environment (i.e.,\
            \ this app) runs"
          type: string
          readOnly: true
          example: "pi (ruid=1000, rgid=1000)"
      example:
        osKernel: "Linux 5.10.63-v7l+ #1459 SMP Wed Oct 6 16:41:57 BST 2021 armv7l\
          \ GNU/Linux"
        hwPiBoardRev: Raspberry Pi 4 Model B Rev 1.1
        hwCpuHw: BCM2711
        hwCpuRev: c03111
        hwBootloaderVer: c2f8c388c4ee37ad709ace403467d163e8dd91ce (release)
        execUser: "pi (ruid=1000, rgid=1000)"
    AppTempDCHistoryEntry:
      title: Root Type for AppTempDCHistoryEntry
      description: History entry capturing fan speed & CPU temperature in a moment
        of time
      required:
      - date
      - tempInCels
      - fanDCInPerc
      type: object
      properties:
        date:
          format: date-time
          description: Date of this entry
          type: string
          readOnly: true
          example: '"2021-11-14T11:14:22+01:00"'
        tempInCels:
          description: Temperature in percent at the date `date`
          type: integer
          readOnly: true
          example: "40"
        fanDCInPerc:
          description: Fan speed in percent at the date `date`
          maximum: 100
          minimum: 0
          type: integer
          readOnly: true
          example: "30"
      example:
        date: 2021-11-14T11:14:22+01:00
        tempInCels: 30
        fanDCInPerc: 40
    SystemProcess:
      title: Root Type for Process
      description: Represents process on host system (or in container if run in Docker
        w/ limited privileges)
      required:
      - name
      - cpuUtilInPerc
      - pid
      - ppid
      type: object
      properties:
        pid:
          description: Pid of the process
          type: integer
          readOnly: true
          example: "5424"
        name:
          description: Name of the process (or rather executable)
          type: string
          readOnly: true
          example: "yes"
        cpuUtilInPerc:
          description: CPU utilization of the process in percent
          maximum: 100
          type: number
          readOnly: true
          example: "100.0"
        ppid:
          description: Pid of the parent process
          type: integer
          readOnly: true
          example: "5434"
      example:
        pid: 5424
        ppid: 5434
        name: "yes"
        cpuUtilInPerc: 100
    AppConfig:
      description: "Comprised of `app` and `pwm` config, which constitute all config\
        \ flags for this app"
      type: object
      properties:
        app:
          $ref: '#/components/schemas/AppConfigApp'
          description: Pertains to configuration of the app itself
          example: |-
            {
                "fanOn": true,
                "loggingEnabled": true,
                "loggingLevel": "WARN",
                "DCUpdateIntervalInSec": 3
            }
        pwm:
          $ref: '#/components/schemas/AppConfigPWM'
          description: Pertains specifically to the configuration of the pwm
          example: |-
            {
                "gpioPin": 12,
                "invertSignal": true,
                "minDCInPerc": 20,
                "maxDCInPerc": 95
            }
      example:
        app:
          fanOn: true
          loggingEnabled: true
          loggingLevel: WARN
          DCUpdateIntervalInSec: 3
          selectedFanCurve:
            id: 916CD0EB-A755-4663-8410-461431039F74
            name: Quiet
            fanCurveSeries:
            - tempInCels: 30
              fanSpeedInPerc: 40
            - tempInCels: 35
              fanSpeedInPerc: 50
        pwm:
          gpioPin: 12
          invertSignal: true
          minDCInPerc: 20
          maxDCInPerc: 95
    AppConfigApp:
      title: Root Type for App
      description: Configuration flags pertaining the app itself
      required: []
      type: object
      properties:
        fanOn:
          description: Whether fan is turned on (kill switch)
          type: boolean
          example: "true"
        loggingLevel:
          description: Current log level
          enum:
          - DEBUG
          - INFO
          - WARNING
          - ERROR
          - CRITICAL
          type: string
          example: WARN
        DCUpdateIntervalInSec:
          format: int32
          description: How frequently the dutycycle shall be updated in seconds
          maximum: 10
          minimum: 1
          type: integer
          example: "3"
        loggingEnabled:
          description: Whether logging is enabled
          type: boolean
          example: "true"
        selectedFanCurve:
          $ref: '#/components/schemas/AppFanCurve'
          description: Currently used fan curve
          example: |-
            {
                "id": "916CD0EB-A755-4663-8410-461431039F74",
                "name": "Quiet",
                "fanCurveSeries": [
                    {
                        "tempInCels": 30,
                        "fanSpeedInPerc": 40
                    },
                    {
                        "tempInCels": 35,
                        "fanSpeedInPerc": 50
                    }
                ]
            }
      example:
        fanOn: true
        loggingEnabled: true
        loggingLevel: WARN
        DCUpdateIntervalInSec: 3
        selectedFanCurve:
          id: 916CD0EB-A755-4663-8410-461431039F74
          name: Quiet
          fanCurveSeries:
          - tempInCels: 30
            fanSpeedInPerc: 40
          - tempInCels: 35
            fanSpeedInPerc: 50
    AppConfigPWM:
      title: Root Type for PWM
      description: Configuration flags of the PWM
      type: object
      properties:
        gpioPin:
          format: int32
          description: GPIO pin used for PWM (which applies the desired dutycycle
            for the fan)
          type: integer
          example: "12"
        invertSignal:
          description: Whether PWM signal shall be inverted (may be required based
            on transitor type (PNP / NPN)
          type: boolean
          example: "true"
        maxDCInPerc:
          format: int32
          description: "Limits max duty cycle, i.e., the max fan speed in percent.\
            \ \nMay be desirable for some fans which only operate reliably within\
            \ a specific range of fan speeds.\nNOTE: This effectively overwrittes\
            \ the applied fan curve."
          maximum: 100
          minimum: 1
          type: integer
          example: "95"
        minDCInPerc:
          format: int32
          description: "Limits min duty cycle, i.e., the min fan speed in percent.\
            \ \nMay be desirable for some fans which only operate reliably within\
            \ a specific range of fan speeds.\nNOTE: This effectively overwrittes\
            \ the applied fan curve."
          maximum: 100
          minimum: 1
          type: integer
          example: "20"
      example:
        gpioPin: 12
        invertSignal: true
        minDCInPerc: 20
        maxDCInPerc: 95
    AppFanCurveSeriesPoint:
      title: Root Type for FanCurveSeriesPoint
      description: Point in fan curve series consisting of temperature in Celsius
        and fan speed in percent
      required:
      - fanDCInPerc
      - tempInCels
      type: object
      properties:
        tempInCels:
          description: The temperature in Celsius for specified `fanSpeedInPerc`
          maximum: 0
          minimum: 0
          type: integer
          example: "40"
        fanDCInPerc:
          description: The fan speed for specified `tempInCels` in percent
          maximum: 100
          minimum: 0
          type: integer
          example: "30"
      example:
        tempInCels: 30
        fanDCInPerc: 40
    AppLogEntry:
      title: Root Type for AppLogEntry
      description: An log entry in app's log
      required:
      - uuid
      - date
      - level
      - message
      type: object
      properties:
        date:
          format: date-time
          description: Date when log entry was logged
          type: string
          readOnly: true
          example: 2021-11-14T11:14:22+01:00
        level:
          description: Level of log entry
          type: string
          readOnly: true
          example: DEBUG
        message:
          description: The logged message
          type: string
          readOnly: true
          example: "Current temp: 45.200000 ℃, calc. fan dutycycle: 30.000000, applied\
            \ dutycycle: 45.000000"
        uuid:
          description: UUID of log entry which is sent to client on error (can be
            used to find log entry more easily)
          type: string
          readOnly: true
          example: 6808e842-453b-11ec-af70-c75dcdc17c9e
      example:
        uuid: 6808e842-453b-11ec-af70-c75dcdc17c9e
        date: 2021-11-14T11:14:22+01:00
        level: DEBUG
        message: "Current temp: 45.200000 ℃, calc. fan dutycycle: 30.000000, applied\
          \ dutycycle: 45.000000"
    HTTPError:
      title: Root Type for HTTPError
      description: Returned to client in case of an error
      required:
      - appErrorCode
      - appErrorDescription
      - httpStatusCode
      - httpStatusDescription
      type: object
      properties:
        httpStatusCode:
          description: The HTTP status code sent to client
          type: integer
          readOnly: true
          example: "404"
        httpStatusDescription:
          description: "Textual description of the HTTP status code (could also be\
            \ looked up by client on e.g., Wikipedia)"
          type: string
          readOnly: true
          example: Not Found
        appErrorCode:
          description: "Error code which is used internally to refer to errors (e.g.,\
            \ 0 indicates 4xx HTTP errors)"
          type: integer
          readOnly: true
          example: "0"
        appErrorDescription:
          description: Textual description of the error code for better comprehension
            on client side
          type: string
          readOnly: true
          example: HTTP API Error
        logUuid:
          description: "UUID of log entry (can be used to find log entry more easily;\
            \ NOTE: May be `null` when error wasn't logged)"
          type: string
          readOnly: true
          example: 6808e842-453b-11ec-af70-c75dcdc17c9e
      example:
        httpStatusCode: 404
        httpStatusDescription: Not Found
        appErrorCode: 0
        appErrorDescription: HTTP API Error
    AppFanCurve:
      description: "Fan curve consisting of id, fan curve series data and name."
      type: object
      allOf:
      - required:
        - id
        type: object
        properties:
          id:
            description: Id of fan curve
            type: string
            example: 916CD0EB-A755-4663-8410-461431039F74
      - $ref: '#/components/schemas/AppFanCurveBase'
      example:
        id: 916CD0EB-A755-4663-8410-461431039F74
        name: Quiet
        fanCurveSeries:
        - tempInCels: 30
          fanSpeedInPerc: 40
        - tempInCels: 35
          fanSpeedInPerc: 50
    AppFanCurveBase:
      description: Fan curve consisting of fan curve series data and name.
      required:
      - name
      - fanCurveSeries
      type: object
      properties:
        name:
          description: Name of the fan curve
          type: string
          example: Quiet
        fanCurveSeries:
          description: Array comprised of all fan series points
          maxItems: 10
          minItems: 1
          uniqueItems: true
          type: array
          items:
            $ref: '#/components/schemas/AppFanCurveSeriesPoint'
          example: |-
            [
                {
                    "tempInCels": 30,
                    "fanSpeedInPerc": 40
                },
                {
                    "tempInCels": 35,
                    "fanSpeedInPerc": 50
                }
            ]
      example:
        name: Quiet
        fanCurveSeries:
        - tempInCels: 30
          fanSpeedInPerc: 40
        - tempInCels: 35
          fanSpeedInPerc: 50
  responses:
    app-config_singleton:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/AppConfig'
          examples:
            config_singleton:
              value:
                app:
                  fanOn: true
                  loggingEnabled: true
                  loggingLevel: WARN
                  DCUpdateIntervalInSec: 3
                  selectedFanCurve:
                    id: 916CD0EB-A755-4663-8410-461431039F74
                    name: Quiet
                    fanCurveSeries:
                    - tempInCels: 30
                      fanSpeedInPerc: 40
                    - tempInCels: 35
                      fanSpeedInPerc: 50
                pwm:
                  gpioPin: 12
                  invertSignal: true
                  minDCInPerc: 20
                  maxDCInPerc: 95
      description: Config of app
    app-fanCurves_collection:
      content:
        application/json:
          schema:
            type: array
            items:
              $ref: '#/components/schemas/AppFanCurve'
          examples:
            fanCurves_collection:
              value:
              - id: 916CD0EB-A755-4663-8410-461431039F74
                name: Quiet
                fanCurveSeries:
                - tempInCels: 30
                  fanSpeedInPerc: 40
                - tempInCels: 35
                  fanSpeedInPerc: 50
              - id: 316CD0EB-A755-4463-8410-461411039F74
                name: Quiet-2
                fanCurveSeries:
                - tempInCels: 30
                  fanSpeedInPerc: 20
                - tempInCels: 35
                  fanSpeedInPerc: 10
              - id: 016ED0EB-A755-4663-8210-461431039F74
                name: Loud
                fanCurveSeries:
                - tempInCels: 20
                  fanSpeedInPerc: 50
                - tempInCels: 35
                  fanSpeedInPerc: 90
                - tempInCels: 45
                  fanSpeedInPerc: 100
      description: Multiple fan curves
    app-fanCurves_singleton:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/AppFanCurve'
          examples:
            fanCurves_singleton:
              value:
                id: 916CD0EB-A755-4663-8410-461431039F74
                name: Quiet
                fanCurveSeries:
                - tempInCels: 30
                  fanSpeedInPerc: 40
                - tempInCels: 35
                  fanSpeedInPerc: 50
      description: Fan curve
    system-topTenProcesses_collection:
      content:
        application/json:
          schema:
            type: array
            items:
              $ref: '#/components/schemas/SystemProcess'
          examples:
            topTenProcesses_collection:
              value:
              - pid: 5424
                ppid: 5434
                name: pihole
                cpuUtilInPerc: 10.35
              - pid: 5426
                ppid: 5434
                name: sh
                cpuUtilInPerc: 7.7
              - pid: 3
                ppid: 1
                name: backupd
                cpuUtilInPerc: 6.9
              - pid: 654
                ppid: 1
                name: bluetoothd
                cpuUtilInPerc: 5.8
              - pid: 9546
                ppid: 435
                name: dockerd
                cpuUtilInPerc: 4
              - pid: 326
                ppid: 435
                name: shred
                cpuUtilInPerc: 3.4
              - pid: 3236
                ppid: 435
                name: watch
                cpuUtilInPerc: 3.1
              - pid: 3436
                ppid: 434
                name: logd
                cpuUtilInPerc: 3
              - pid: 3236
                ppid: 435
                name: transmission
                cpuUtilInPerc: 2.4
              - pid: 322
                ppid: 435
                name: dd
                cpuUtilInPerc: 1
      description: Top ten processes
    system-topTenProcesses_singleton:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/SystemProcess'
          examples:
            topTenProcesses_singleton:
              value:
                pid: 5424
                ppid: 5434
                name: "yes"
                cpuUtilInPerc: 100
      description: A process within the top ten processes
    app-tempDCHistory_collection:
      content:
        application/json:
          schema:
            type: array
            items:
              $ref: '#/components/schemas/AppTempDCHistoryEntry'
          examples:
            tempDCHistory_collection:
              value:
              - date: 2021-11-14T11:14:22+01:00
                tempInCels: 30
                fanDCInPerc: 40
              - date: 2021-11-14T11:14:25+01:00
                tempInCels: 33
                fanDCInPerc: 42
              - date: 2021-11-14T11:14:28+01:00
                tempInCels: 31
                fanDCInPerc: 40
              - date: 2021-11-14T11:14:31+01:00
                tempInCels: 34
                fanDCInPerc: 43
              - date: 2021-11-14T11:14:34+01:00
                tempInCels: 33
                fanDCInPerc: 42
      description: Temperature- / DC history
    system-info_singleton:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/SystemInfo'
          examples:
            systeminfo_singleton:
              value:
                osKernel: "Linux 5.10.63-v7l+ #1459 SMP Wed Oct 6 16:41:57 BST 2021\
                  \ armv7l GNU/Linux"
                hwPiBoardRev: Raspberry Pi 4 Model B Rev 1.1
                hwCpuHw: BCM2711
                hwCpuRev: c03111
                hwBootloaderVer: c2f8c388c4ee37ad709ace403467d163e8dd91ce (release)
      description: System info
    app-logs_collection:
      content:
        application/json:
          schema:
            type: array
            items:
              $ref: '#/components/schemas/AppLogEntry'
          examples:
            logs_collection:
              value:
              - uuid: 6808e842-453b-11ec-af70-c75dcdc17c9e
                date: 2021-11-14T11:14:25+01:00
                level: DEBUG
                message: "Current temp: 45.200000 ℃, calc. fan dutycycle: 30.000000,\
                  \ applied dutycycle: 45.000000"
              - uuid: 7808e842-453b-11ec-af70-c75dcdc17c9e
                date: 2021-11-14T11:14:28+01:00
                level: DEBUG
                message: "Current temp: 42.200000 ℃, calc. fan dutycycle: 25.000000,\
                  \ applied dutycycle: 40.000000"
              - uuid: 8808e842-453b-11ec-af70-c75dcdc17c9e
                date: 2021-11-14T11:14:31+01:00
                level: DEBUG
                message: "Current temp: 45.200000 ℃, calc. fan dutycycle: 30.000000,\
                  \ applied dutycycle: 45.000000"
              - uuid: 9808e842-453b-11ec-af70-c75dcdc17c9e
                date: 2021-11-14T11:14:34+01:00
                level: DEBUG
                message: "Current temp: 44.200000 ℃, calc. fan dutycycle: 30.000000,\
                  \ applied dutycycle: 45.000000"
              - uuid: 0908e842-453b-11ec-af70-c75dcdc17c9e
                date: 2021-11-14T11:14:37+01:00
                level: DEBUG
                message: "Current temp: 40.200000 ℃, calc. fan dutycycle: 25.000000,\
                  \ applied dutycycle: 40.000000"
      description: Log
    HTTPError-NotFound:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/HTTPError'
          examples:
            HTTPError-NotFound:
              value:
                httpStatusCode: 404
                httpStatusDescription: Not Found
                appErrorCode: 0
                appErrorDescription: HTTP API Error
      description: Error (Requested resource doesn't exist)
    HTTPError-Locked:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/HTTPError'
          examples:
            HTTPError-Locked:
              value:
                httpStatusCode: 423
                httpStatusDescription: Locked
                appErrorCode: 0
                appErrorDescription: To be deleted resource cannot be deleted b/c
                  it's currently in use
      description: "Error (Resource, e.g., fan curve, cannot be deleted b/c it's currently\
        \ in use)"
    HTTPError-BadRequest:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/HTTPError'
          examples:
            HTTPError-BadRequest:
              value:
                httpStatusCode: 400
                httpStatusDescription: Bad Request
                appErrorCode: 0
                appErrorDescription: Malformed payload in request body
      description: "Error (Bad Request, e.g., due to malformed payload in request\
        \ body)"
  securitySchemes:
    api-security:
      scheme: basic
      type: http
      description: Validated by webapp
security:
- api-security: []
